-- +goose Up
-- +goose StatementBegin
create table user_tokens (
  id bigint primary key generated by default as identity,
  user_id bigint not null references users (id) on delete cascade,
  token bytea not null,
  context varchar(50) not null,
  inserted_at timestamp(0) not null default (now() at time zone 'utc')
);

create index on user_tokens (user_id);
create unique index on user_tokens (context, token);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table user_tokens;
-- +goose StatementEnd
