// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int64
	Email        string
	DisplayName  string
	PasswordHash string
	InsertedAt   pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
