// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int64
	Email        string
	DisplayName  string
	PasswordHash string
	InsertedAt   pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type UserToken struct {
	ID         int64
	UserID     int64
	Token      []byte
	Context    string
	InsertedAt pgtype.Timestamp
}

type WebauthnCredential struct {
	ID                        int64
	WebauthnID                []byte
	UserID                    int64
	PublicKey                 []byte
	AttestationType           *string
	Transport                 []string
	UserPresent               bool
	UserVerified              bool
	BackupEligible            bool
	BackupState               bool
	AuthenticatorAAGUID       []byte
	AuthenticatorSignCount    int32
	AuthenticatorCloneWarning bool
	AuthenticatorAttachment   *string
	InsertedAt                pgtype.Timestamp
	UpdatedAt                 pgtype.Timestamp
}
